// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3FTs5iUlT7MljdebAK5RfZfLXHc9i2uo',
    appId: '1:616151795227:android:c86056a7f5968a55505abe',
    messagingSenderId: '616151795227',
    projectId: 'instajob-1ec28',
    storageBucket: 'instajob-1ec28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNe25H9FkxGFlgvCG4SRUgAn0EuELuIAs',
    appId: '1:616151795227:ios:2e012e5e4ef40ab8505abe',
    messagingSenderId: '616151795227',
    projectId: 'instajob-1ec28',
    storageBucket: 'instajob-1ec28.appspot.com',
    androidClientId: '616151795227-9nj5kecjunjeam2m77kf708461qi3nrq.apps.googleusercontent.com',
    iosClientId: '616151795227-7iphlom0hia022abahiht6aierji7uil.apps.googleusercontent.com',
    iosBundleId: 'com.instajob.online',
  );

}